version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: event_platform_db
    environment:
      POSTGRES_USER: event_user
      POSTGRES_PASSWORD: event_pass
      POSTGRES_DB: event_platform
    ports:
      - "5433:5432"   
